name: reusemart_mobile
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1  
  flutter_svg: ^2.0.9
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  flutter_test:
    sdk : flutter

flutter:
  uses-material-design: true
  # Tidak perlu menambahkan fonts untuk Material Icons
  # Jika menggunakan font kustom lain, tambahkan di sini
  assets:
    # Tambahkan aset lain jika ada, misalnya gambar
    - assets/images/carousel1.png