// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9REaTwlqsVx_F9r7_7YBf3-YziH-GlvY',
    appId: '1:75684524918:web:11f5d4967aa2d260a4c057',
    messagingSenderId: '75684524918',
    projectId: 'reusemart-4365d',
    authDomain: 'reusemart-4365d.firebaseapp.com',
    storageBucket: 'reusemart-4365d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_vlXO5sTW_oJZ5gNzjKqbi3mtgwITj9w',
    appId: '1:75684524918:android:2810d92df1b25a61a4c057',
    messagingSenderId: '75684524918',
    projectId: 'reusemart-4365d',
    storageBucket: 'reusemart-4365d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBftWigHYCQ5pNK82Afw5h8FfQLZKevm7M',
    appId: '1:75684524918:ios:84f1f9d74b13df83a4c057',
    messagingSenderId: '75684524918',
    projectId: 'reusemart-4365d',
    storageBucket: 'reusemart-4365d.firebasestorage.app',
    iosBundleId: 'com.example.reusemartMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBftWigHYCQ5pNK82Afw5h8FfQLZKevm7M',
    appId: '1:75684524918:ios:84f1f9d74b13df83a4c057',
    messagingSenderId: '75684524918',
    projectId: 'reusemart-4365d',
    storageBucket: 'reusemart-4365d.firebasestorage.app',
    iosBundleId: 'com.example.reusemartMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9REaTwlqsVx_F9r7_7YBf3-YziH-GlvY',
    appId: '1:75684524918:web:eee2d71adc41df1fa4c057',
    messagingSenderId: '75684524918',
    projectId: 'reusemart-4365d',
    authDomain: 'reusemart-4365d.firebaseapp.com',
    storageBucket: 'reusemart-4365d.firebasestorage.app',
  );

}